jdbc.url=jdbc:postgresql://localhost:5432/snlp
jdbc.username=postgres
jdbc.password=root

#asrAPIUrl = http://10.10.10.214:80/asr_service
asrAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/asraction
#asrAPIUrl = https://10.10.11.35:80/asr_service

#ttsAPIUrl = http://10.10.10.214:80/tts_service
ttsAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/ttsaction

#mtAPIUrl = http://10.10.10.214:80/cdac_ulca_mt_service
mtAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/ulcamtaction

#http://10.10.10.214:80/mt_service

#transliterationAPIUrl = http://10.10.10.214:80/translit_service
transliterationAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/ulcatranslation

ocrAPIUrl = http://10.226.30.33:8080/post_json
ocrTessUrl = http://10.226.30.43:8082/ocr

asrInputPath = D\:\\snlpResources\\asrInput\\
ttsOutputPath = D\:\\snlpResources\\ttsOutput\\
speechToTextInputPath = D\:\\snlpResources\\speechToTextInput\\
ocrInputPath = D\:\\snlpResources\\ocrInput\\
pdfInputPath = D\:\\snlpResources\\pdfInput

pdfToImgPathTemp = D\:\\snlpResources\\pdfInputTemp\\
imagesToPDF = D\:\\snlpResources\\imagesToPDF\\

#asrInputPath = /opt/uat_snlpmobp_8080/SNLP_project/asrInput/
#ttsOutputPath = /opt/uat_snlpmobp_8080/SNLP_project/ttsOutput/
#speechToTextInputPath = /opt/uat_snlpmobp_8080/SNLP_project/speechToTextInput/
#ocrInputPath = /opt/uat_snlpmobp_8080/SNLP_project/ocrInput/
#pdfInputPath = /opt/uat_snlpmobp_8080/SNLP_project/pdfInput/
#
#pdfToImgPathTemp = /opt/uat_snlpmobp_8080/SNLP_project/pdfInputTemp/
#imagesToPDF = /opt/uat_snlpmobp_8080/SNLP_project/imagesToPDF/


#following api(pdf2imageAPI) hosted in desktop
pdf2imageAPI = http://10.226.17.19:94/extract_images
