#asrAPIUrl = http://10.10.10.214:80/asr_service
#asrAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/asraction

#Replaced "https://uatsnlp.dcservices.in" with "http://10.10.10.136:8080"
asrAPIUrl = http://10.10.10.136:8080/CDACDictation/asraction 

ttsAPIUrl = http://10.10.10.214:80/tts_service
#ttsAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/ttsaction
#ttsAPIUrl = http://10.10.10.136:8080/CDACDictation/ttsaction

#mtAPIUrl = http://10.10.10.214:80/cdac_ulca_mt_service
#mtAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/ulcamtaction
mtAPIUrl = http://10.10.10.136:8080/CDACDictation/ulcamtaction
#http://10.10.10.214:80/mt_service

#transliterationAPIUrl = http://10.10.10.214:80/translit_service
#transliterationAPIUrl = https://uatsnlp.dcservices.in/CDACDictation/ulcatranslation
transliterationAPIUrl = http://10.10.10.136:8080/CDACDictation/ulcatranslation

ocrAPIUrl = http://10.226.30.33:8080/post_json
ocrTessUrl = http://10.10.11.128:8082/ocr

asrInputPath = D\:\\snlpResources\\asrInput\\
ttsOutputPath = D\:\\snlpResources\\ttsOutput\\
speechToTextInputPath = D\:\\snlpResources\\speechToTextInput\\
ocrInputPath = D\:\\snlpResources\\ocrInput\\
pdfInputPath = D\:\\snlpResources\\pdfInput
pdfToImgPathTemp = D\:\\snlpResources\\pdfInputTemp\\
imagesToPDF = D\:\\snlpResources\\imagesToPDF\\

#asrInputPath = /opt/uatsnlp_8081/SNLP_project/asrInput/
#ttsOutputPath = /opt/uatsnlp_8081/SNLP_project/ttsOutput/
#speechToTextInputPath = /opt/uatsnlp_8081/SNLP_project/speechToTextInput/
#ocrInputPath = /opt/uatsnlp_8081/SNLP_project/ocrInput/
#pdfInputPath = /opt/uatsnlp_8081/SNLP_project/pdfInput/
#pdfToImgPathTemp = /opt/uatsnlp_8081/SNLP_project/pdfInputTemp/
#imagesToPDF = /opt/uatsnlp_8081/SNLP_project/imagesToPDF/


#following api(pdf2imageAPI) hosted in desktop
pdf2imageAPI = http://10.226.17.19:94/extract_images
